## manipulando arrays
---

#### splicing e indexing
---

In [1]:
import numpy as np

v0 = np.random.randint(0, 10, 5)
v1 = np.random.randint(0, 10, (4, 3, 4))
v2 = np.random.randint(0, 10, (2, 3))

os vetores e matrizes de numpy podem ser indexados e cortados de forma semelhante às listas em python:

sabendo que o vetor `v0` é:

In [2]:
v0

array([6, 1, 3, 8, 8])

pode-se, então, 

In [3]:
v0[3]

8

In [4]:
v0[:3]

array([6, 1, 3])

In [5]:
v0[3:]

array([8, 8])

In [6]:
v0[-1]

8

In [7]:
v0[-2]

8

In [8]:
v0[::-1]

array([8, 8, 3, 1, 6])

só para mostrar alguns exemplos.

Pode mudar quando a dimensão for maior, pois, diferente das listas em python que recebem duas chaves, os arrays em numpy continuam recebendo apenas uma chave sendo os valores separados por vírgula:

por exemplo, veja que `v2` é:

In [9]:
v2

array([[9, 0, 6],
       [1, 3, 4]])

então,

In [10]:
v2[1, 1]

3

mas, também funciona

In [11]:
v2[1][2]

4

com matrizes de dimensões maiores que 2, a ideia é a mesma:

In [12]:
v1

array([[[5, 6, 9, 2],
        [8, 8, 5, 8],
        [9, 2, 8, 2]],

       [[2, 8, 4, 5],
        [8, 3, 4, 7],
        [1, 3, 0, 4]],

       [[2, 6, 0, 9],
        [9, 4, 9, 5],
        [6, 9, 8, 9]],

       [[1, 8, 0, 1],
        [5, 1, 7, 8],
        [0, 8, 3, 2]]])

In [13]:
v1[2]

array([[2, 6, 0, 9],
       [9, 4, 9, 5],
       [6, 9, 8, 9]])

In [14]:
v1[2, 1] # ou v1[2][1]

array([9, 4, 9, 5])

In [15]:
v1[2, 1, 0] # ou v1[2][1][0]

9

observe que, também é possível, mudar um valor usando indexing e splicing:

In [16]:
v0[0] = 1
v0

array([1, 1, 3, 8, 8])

é importante observar que cada valor index dentro das chaves podem servir como splicing, também:

In [17]:
v1[:3, ::2]

array([[[5, 6, 9, 2],
        [9, 2, 8, 2]],

       [[2, 8, 4, 5],
        [1, 3, 0, 4]],

       [[2, 6, 0, 9],
        [6, 9, 8, 9]]])

In [18]:
v2[-1, ::-1]

array([4, 3, 1])

#### cópias e visualizações
---

diferente de python, quando um array passa pelo processo de splicing ou de index, o que o numpy mostra é só um visualizador, observe:

In [19]:
v0

array([1, 1, 3, 8, 8])

In [20]:
v0_ = v0[1:3]
v0_

array([1, 3])

se for feito alguma mudança em qualquer um desses vetores, o outro também será influenciado:

In [21]:
v0_[0] = 0
v0_

array([0, 3])

In [22]:
v0

array([1, 0, 3, 8, 8])

para, de fato, copiar um array é necessário usar o método `.copy()`

In [23]:
v0_ = v0[1:3].copy()
v0_

array([0, 3])

assim,

In [24]:
v0_[0] = 3
v0_

array([3, 3])

In [25]:
v0

array([1, 0, 3, 8, 8])

#### concatenação e divisão
---

aqui, são processo diferentes da matemática, pois o que se deseja não é a divisão de um array por outro ou a soma de um array por outro, mas a divisão de um array em vários ou a junção de dois ou mais arrays separados.

como usar *+* faz a soma, é necessário usar o método `.concatenate()`

In [26]:
ar1 = np.array([1, 2, 3, 4])
ar2 = np.array([5, 6, 7, 8])

ar1 + ar2

array([ 6,  8, 10, 12])

porém,

In [27]:
np.concatenate([ar1, ar2])

array([1, 2, 3, 4, 5, 6, 7, 8])

observe que a ordem importa:

In [28]:
np.concatenate([ar2, ar1])

array([5, 6, 7, 8, 1, 2, 3, 4])

isto serve para arrays com mais de uma dimensão, bem como pode ser feito com mais de duas arrays.

quando trabalha-se com arrays de diferentes dimensões, é melhor usar os métodos `.vstack()` e `.hstack()`, servindo para forma uma array vertical ou horizontal, respectivamente.

In [29]:
ar1 = np.array([[1, 2, 3], [3, 2, 1]])
ar2 = np.array([4, 5, 6])

np.vstack([ar1, ar2])

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

In [30]:
ar3 = np.array([[0], [1]])

np.hstack([ar3, ar1])

array([[0, 1, 2, 3],
       [1, 3, 2, 1]])

o método `.dstack()` funciona com a terceira coordenada.

já, para separar um array em outras arrays, usa-se os métodos `.split()`, `.hsplit()` e `.vsplit()`:

estas funções devem receber como parâmetro a array original seguido, em uma tupla, os pontos que a divisão deverá ocorrer:

In [31]:
div = np.arange(16)
div

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
d1, d2, d3, d4, d5, d6 = np.split(div, [2, 5, 8, 11, 14])

In [33]:
d1

array([0, 1])

In [34]:
d2

array([2, 3, 4])

In [35]:
d3

array([5, 6, 7])

In [36]:
d4

array([ 8,  9, 10])

In [37]:
d5

array([11, 12, 13])

In [38]:
d6

array([14, 15])

é importante observar que para n pontos de divisão, são formadas n+1 novas arrays.

os demais métodos funcionam da forma semelhante:

In [39]:
v1, v2 = np.hsplit(div, [7])

In [40]:
v1

array([0, 1, 2, 3, 4, 5, 6])

In [41]:
v2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
div2 = np.array([[0, 15], [2, 5]])
div2

array([[ 0, 15],
       [ 2,  5]])

In [43]:
h1, h2 = np.vsplit(div2, [1])

In [44]:
h1

array([[ 0, 15]])

In [45]:
h2

array([[2, 5]])

é importante lembrar que `.vsplit()` só funciona com arrays de dimensões maiores ou iguais a 2.

#### sorting
---

há duas formas: a primiera, usando `<vetor>.sort()` que não retorna nada, mas reorganiza o vetor original.

In [46]:
vtr = np.array([4, 6, 2, 6, 2, 6, 8, 4, 2, 3, 5, 7, 8])
std = vtr.sort()
print(std)

None


In [47]:
print(vtr)

[2 2 2 3 4 4 5 6 6 6 7 8 8]


a outra forma, de fato, constrói um novo vetor, `np.sort(<vetor>)`, enquanto que o vetor original permanece inalterado.

In [48]:
vtr = np.array([4, 6, 2, 6, 2, 6, 8, 4, 2, 3, 5, 7, 8])
std = np.sort(vtr)
std

array([2, 2, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 8])

nesta última forma, é, ainda, possível passar como parâmetro, `kind=`, que interfere diretamente na velocidade do programa.