In [1]:
import numpy as np

#### operações matenáticas entre arrays
---

com numpy, é possível fazer as operações matemáticas mais básicas com os vetores:

In [2]:
fs1 = np.arange(1, 6)
nd2 = np.arange(6, 11)

#soma
fs1 + nd2

array([ 7,  9, 11, 13, 15])

In [3]:
#subtração
nd2 - fs1

array([5, 5, 5, 5, 5])

In [4]:
#multiplicação
fs1 * nd2

array([ 6, 14, 24, 36, 50])

In [5]:
#divisão
nd2 / fs1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

se não desejar obter as casas decimais, pode-se usar a função `.around()`

In [6]:
np.around(nd2 / fs1)

array([6., 4., 3., 2., 2.])

ou, ainda pode ser especificado a quantidade valores decimais que deseja-se:

In [7]:
np.around(nd2 / fs1, 3)

array([6.   , 3.5  , 2.667, 2.25 , 2.   ])

observe que, para manipular dois ou mais vetores matematicamente, é necessário que estes vetores tenham amesma quantidade de valores.

#### operações matemáticas, estatísticas e probabilísticas
---

se desejar saber a soma dos valores de uma array, use a função `.sum()`:

In [8]:
np.sum(nd2) 

40

se desejar obter um vetor contendo as somas intermediárias, use `.add.accumulate()` ou `.cumsum()`:

In [9]:
np.add.accumulate(nd2) # ou np.cumsum(nd2)

array([ 6, 13, 21, 30, 40])

da mesma forma que, se desejar saber a média, deve-se usar a função `.mean()`

In [10]:
np.mean(nd2)

8.0

o produto se calcula com função semelhante: `.prod()`:

In [11]:
np.prod(nd2)

30240

se desejar obter um vetor contendo os produtos intermediários, use `.multiply.accumulate()` ou `.cumprod()`:

In [12]:
np.multiply.accumulate(nd2) # ou np.cumprod(nd2)

array([    6,    42,   336,  3024, 30240])

para encontrar o mínimo e o máximo use as funções `.min()` e `.max()`

In [13]:
np.max(nd2)

10

In [14]:
np.min(nd2)

6

também é possível saber a posição dos menores e dos maiores valores, usando `.argmin()` e `.argmax()`

In [15]:
np.argmin(nd2)

0

In [16]:
np.argmax(nd2)

4

todas as funções para cálculo de um array, além das já apresentadas:
np.funções|operação
---|---|
np.std()|desvio padrão|
np.var()|variância|
np.median()|mediana()|
np.percentile()|porcentagem()|
np.any()|or|
np.all()|and|

todas estas funções podem receber o parâmetro `axis=`. este parâmetro, se receber 0 (zero), ele fará a operação indicada pela função nas colunas; já, se receber 1 (um), ele fará a operação indicada pela função nas linhas.

In [17]:
x = np.random.random((2, 4))
print(f'''{x}
soma das colunas: {x.sum(axis=0)}
soma das linhas: {x.sum(axis=1)}
máximo das colunas: {x.max(axis=0)}
máixmo das linhas: {x.max(axis=1)}
etc.''')

[[0.21336447 0.00587753 0.18997183 0.77174093]
 [0.37718874 0.50763712 0.53590646 0.34953781]]
soma das colunas: [0.5905532  0.51351465 0.72587829 1.12127874]
soma das linhas: [1.18095476 1.77027013]
máximo das colunas: [0.37718874 0.50763712 0.53590646 0.77174093]
máixmo das linhas: [0.77174093 0.53590646]
etc.


estas funções podem ter seus nomes trocados para incluir `NaN`, para, com isto, proteger a operação caso haja algum valor faltando:

In [18]:
np.nanmean(x)

0.3689031109688933

#### funções e constantes matemáticas
---

usando a função `.abs()`, é possível fazer com que qualquer vetor tenha apenas valores positivivos

In [19]:
vtr = np.array([-2, -5, 6, 0, 1/2, 5])
vtr

array([-2. , -5. ,  6. ,  0. ,  0.5,  5. ])

In [20]:
np.abs(vtr)

array([2. , 5. , 6. , 0. , 0.5, 5. ])

numpy também ofecere uma série de funções que podem ser usadas para transformar arrays:
np.funções|
---|
cos()|
sin()|
tan()|
arccos()|
arcsin()|
arctan()|
log()|
log2()|
log10()|
exp()|

In [21]:
np.cos(vtr)

array([-0.41614684,  0.28366219,  0.96017029,  1.        ,  0.87758256,
        0.28366219])

In [22]:
np.log(np.array([1, 2, 3, 4]))

array([0.        , 0.69314718, 1.09861229, 1.38629436])

observe que as funções trigonométricas são nativamente em radianos.

para valores muito pequenos, há, ainda, algumas funções que melhoram a precisão:

np.precisão|
---|
np.expm1()|
np.log1p()|

numpy oferece, também, constantes como
np.constantes|
---|
pi()|
e()|

In [23]:
np.e

2.718281828459045

e, estas constantes podem ser usadas para modificar arrays:

In [24]:
np.pi * np.array([1, 2, 3, 4])

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061])

#### comparação
---

assim como as funções aritméticas acima, temos que os operadores booleanos também funcionam entre arrays ou entre arrays e números:

In [25]:
array = np.linspace(0, 10, 10)
array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [26]:
array > 3.5

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

nas operações booleanas, os resultados são sempre outro array informando se o valor daquele índice é verdadeiro ou falso. Ou seja, o valor do índice 2 no array original deve ser menor que 3.5 porque no array booleano, o índice dois é preenchido com `False`.

todas as seis operações booleanas são suportadas pelos arrays de numpy:

In [27]:
array != 1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [28]:
array >= 1000

array([False, False, False, False, False, False, False, False, False,
       False])

todas as funções booleanas nativas do python têm uma função correspondente do numpy:
python|np.função()
---|---|
==|equal|
!=|not_equal|
<|less|
<=|less_equal|
\>|greater|
\>=|greater_equal|
&|bitwise_and|
\||bitwise_or|
^|bitwise_xor|
~|bitwise_not

por exemplo:

In [33]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.equal(a, 1)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

é interessante notar que, para o numpy, todos os valores booleanos são interpretados como 0 e 1, assim: False = 0 e True = 1. assim, é possível fazer operações matemáticas com esses arrays booleanos:

In [35]:
np.sum(np.equal(a, 1))

3

In [36]:
np.prod(np.less_equal(a, 1), axis=0)

array([1, 1, 1])

In [37]:
np.all(a < 1)

False

In [38]:
np.any(a < 1) & (np.not_equal(a, -1) | np.greater(a, 0))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

especificamente a operação de soma é usada para verificar quantos True, ou seja, 1, houve com esta verificação.

essas operações booleanas podem ser usadas para encontrar valores que corresponderem à verificação:

In [39]:
x = np.array([[5, 0, 3, 3],[7, 9, 3, 5],[2, 4, 7, 6]])
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [40]:
x[x > 5]

array([7, 9, 7, 6])