## valores aleatórios
---

In [1]:
import numpy.random as rd

é uma classe e, com isso, um objeto pode ser feito:

In [2]:
alea = rd.default_rng()

este objeto, `alea`, servirá para criar números aleatórios, já que este é um objeto da classe `rd.default_rng()`, que significa gerador numérico aleatório padrão.

assim, com o método `.integers()`, é gerado um valor inteiro aleatório entre o valor mínimo e máximo passad pelo usuário.

In [3]:
alea.integers(1, 10)

6

com este método, também é possível criar arrays usando o parâmetro `size=`

In [4]:
alea.integers(1, 10, size=10)

array([8, 5, 5, 7, 4, 5, 8, 8, 3, 1], dtype=int64)

neste método, o último ponto é excluído, por isso, pode ser passado como parâmetro `endpoint=True` ara que esta seja incluído, bem como, é possível mudar o tamanho da memória usando `dtype=`

o método `.random()` recebe uma quantidade de números entre zero e um aleatórios que deseja-se obter:

In [5]:
alea.random(10)

array([0.87714167, 0.53271976, 0.03177421, 0.36144794, 0.84832632,
       0.28361966, 0.57560255, 0.41002803, 0.44057677, 0.20650512])

In [6]:
alea.random((3, 5))

array([[0.09956673, 0.95952738, 0.1387932 , 0.77773661, 0.07857146],
       [0.05437252, 0.637819  , 0.36972004, 0.0991005 , 0.03814815],
       [0.57996712, 0.94388165, 0.71701559, 0.16678198, 0.50478132]])

o método `normal()` cria vetores e matrizes com valor aleatórios, precisando passar como parâmetro a média entre estes valores, o desvio padrão e, então, o tamanho do vetor/matriz:

In [7]:
alea.normal(1, 2, (3, 4))

array([[ 0.91423919,  1.00951582,  1.03256222,  0.44356526],
       [ 1.24371473,  0.54361868, -0.70818539,  1.97752429],
       [ 0.42823792,  0.01393757,  3.50306084,  0.09388028]])

In [8]:
alea.normal(1, 1, 3)

array([1.4793729 , 0.57828365, 1.82544775])

o método `.randint()` cria vetores e matrizes com valores inteiros aleatórios num intervalo definido pelo usuário:

In [11]:
rd.randint(0, 10, (5, 5))

array([[3, 5, 9, 0, 9],
       [8, 6, 9, 1, 8],
       [1, 2, 5, 0, 2],
       [1, 2, 7, 7, 5],
       [6, 0, 1, 8, 5]])

o método `.shuffle()` pode desorganizar uma array.

In [13]:
import numpy as np

array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
alea.shuffle(array)
print(array)

[2 4 7 9 8 5 1 6 3]


com o método `.choice()`, deve ser passado uma array em seguida do tamanho que se deseja que seja gerada uma nova array com elementos aleatórios da array anterior:

In [18]:
new_array = alea.choice(array, size=5)
new_array

array([6, 6, 2, 8, 8])

In [24]:
new_array = alea.choice(array, size=(3, 4))
new_array

array([[3, 5, 1, 9],
       [2, 6, 2, 9],
       [7, 8, 9, 7]])

passando como parâmetro `replace=False`, um array gerado nunca mais aparecerá novamente.