## vetores
---

In [1]:
import numpy as np

#### array()
---

uma forma de criar um vetor é passando um lista como parâmetro na função `.array()`

In [2]:
lista = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
vetor = np.array(lista)
vetor

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34])

a função `.array()` também funciona para criar matrizes:

In [3]:
lista = [[i, i+3] for i in range(3)]
mtx = np.array(lista)
mtx

array([[0, 3],
       [1, 4],
       [2, 5]])

inclusive, se passarmos uma matriz como parâmetro à função `list()`, é retornado várias listas, cada uma correspondendo a uma linha da matriz original.

In [4]:
list(lista)

[[0, 3], [1, 4], [2, 5]]

é importante observar que, diferente de python onde as listas podem conter diferentes tipos de dados, numpy não suporta tal coisa, por isso, se, por exemplo, tanta-se passar um valor *float* em um vetor ou matriz apenas com *int* pode resultar em erros:

In [6]:
vt = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(vt)

vt[0] = 3.14
print(vt)

[1 2 3 4 5]
[3 2 3 4 5]


observe que o valor *float* foi truncado.

#### atributos
---

`size` mostra a quantidade de informação que tem num array:

In [43]:
vetor = np.arange(5)
matriz = np.array([[1, 3], [2, 5], [3, 6]])

print(f'{vetor.size}\n{matriz.size}')

5
6


para saber o formato do array use o atributo `.shape`:

In [44]:
print(f'{vetor.shape}\n{matriz.shape}')

(5,)
(3, 2)


este atributo suporta métodos de splicing e indexing.

como já se sabe, o formato de um array é um especificada em uma tupla onde o primeiro valor é referente às linhas e o segundo valor é referente às colunas: (linhas, colunas). Sabendo disso, pode-se mudar o formato de um array utilizando o atributo `.newaxis`:

In [45]:
# adicionando uma coluna ao array vetor
nova_coluna = vetor[:, np.newaxis]
print(f'{vetor}\n{nova_coluna}')

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [46]:
# adicionando uma linhas ao array vetor
nova_linha = vetor[np.newaxis, :]
print(f'{vetor}\n{nova_linha}')

[0 1 2 3 4]
[[0 1 2 3 4]]


#### arange()
---

serve para criar vetores se este tiver valores sequenciais:

In [7]:
v0 = np.arange(15)
v0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

observe que, semelhante ao slicing de listas, ao passarmos apenas um valor n, temos que aparece os valores de 0 a n-1.

pode-se, também, assim como o slicing de listas, criar intervalos:

In [8]:
v1 = np.arange(17, 23)
v1

array([17, 18, 19, 20, 21, 22])

pode-se indicar o passo:

In [9]:
v2 = np.arange(17, 30, 2)
v2

array([17, 19, 21, 23, 25, 27, 29])

pode-se fazer com valores decrescentes:

In [10]:
v3 = np.arange(30, 17, -1)
v3

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18])

como se pode observar, os vetores de numpy são muito semelhantes às listas em python. Porém, é interessante notar que, diferente dos containeres em python, numpy aceita valores decimais em seus métodos de slicing:

In [11]:
v4 = np.arange(30, 17, -0.5)
v4

array([30. , 29.5, 29. , 28.5, 28. , 27.5, 27. , 26.5, 26. , 25.5, 25. ,
       24.5, 24. , 23.5, 23. , 22.5, 22. , 21.5, 21. , 20.5, 20. , 19.5,
       19. , 18.5, 18. , 17.5])

In [12]:
import sympy as sp

v5 = np.arange(0, 17, sp.N(sp.pi/2))
v5

array([0, 1.57079632679490, 3.14159265358979, 4.71238898038469,
       6.28318530717959, 7.85398163397448, 9.42477796076938,
       10.9955742875643, 12.5663706143592, 14.1371669411541,
       15.7079632679490], dtype=object)

#### zeros() e ones()
---

é uma função que cria vetores preenchidos com zeros, apenas:

In [13]:
zr = np.zeros(10)
zr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

observe que deve ser passado a quantidade de zeros que deseja-se. se quiser, pode passar o tipo de dado que será estes zeros:

In [14]:
zr = np.zeros(10, dtype=np.int8)
zr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

ao invés de passar apenas um valor, uma tupla também pode ser usada para criar uma matriz de zeros, sendo o primeiro valor referente às linhas e o segundo valor referente às colunas.

In [15]:
mtx_zr = np.zeros((3, 5))
mtx_zr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

já a função `.ones()` se comporta da mesma forma que `.zeros()` podendo criar vetores e matriz contendo apenas o valor de um:

In [16]:
um = np.ones((3, 4), dtype=np.complex64)
um

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]], dtype=complex64)

#### full()
---

de forma semelhante às funções `.zeros()` e `.ones()`, `.full()` serve para criar um vetor ou matriz cheia de apenas um único valor:

In [17]:
vlr = np.full(10, 3.14)
vlr

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [18]:
mtx_vlr = np.full((3, 3), 2.72)
mtx_vlr

array([[2.72, 2.72, 2.72],
       [2.72, 2.72, 2.72],
       [2.72, 2.72, 2.72]])

#### linspace()
---

é semelhante à função `.arange()`, porém, esta serve para criar um vetor onde o início e o final já são estabelecidos e, com  isto, este intervalo será dividido pelo valor passado no terceiro parâmetro:

In [19]:
spc = np.linspace(0, 10, 5)
spc

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

compare com

In [20]:
pulo = np.arange(0, 10, 5)
pulo

array([0, 5])

observe que, se o terceiro valor não for passado, o valor padrão será 50:

In [21]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

também funciona para criar matrizes. Observe que a distância, então, trata-se da posição 1 do primeiro vetor até a posição 1 do segundo vetor, depois faz entre a posição do primeiro vetor até a posição do segundo vetor, e, assim, sucessivamente.

In [22]:
np.linspace((1, 5, 3), (10, -5, 6), 10)

array([[ 1.        ,  5.        ,  3.        ],
       [ 2.        ,  3.88888889,  3.33333333],
       [ 3.        ,  2.77777778,  3.66666667],
       [ 4.        ,  1.66666667,  4.        ],
       [ 5.        ,  0.55555556,  4.33333333],
       [ 6.        , -0.55555556,  4.66666667],
       [ 7.        , -1.66666667,  5.        ],
       [ 8.        , -2.77777778,  5.33333333],
       [ 9.        , -3.88888889,  5.66666667],
       [10.        , -5.        ,  6.        ]])

#### eye()
---

serve para criar a matriz identidade:

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### empty()
---

serve para criar uma matriz ou vetor com o último valor que estiver armazenado na memória do computador:

In [24]:
np.empty(3)

array([ 1.        , -1.11111111,  0.33333333])

In [25]:
np.empty((3, 4))

array([[4.68173050e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.14587773e-312, 7.32121640e+169, 2.65260223e-032,
        1.58660469e-047],
       [2.21533752e+160, 2.98182574e+179, 4.11570451e+179,
        1.17475443e+165]])

#### reshape()
---

é o método usado para reorganizar o vetor ou a matriz em outro formato. para isto, é preciso que o tamanho da array inicial combine com sua reformulação:

In [26]:
v0 = np.arange(1, 10)
v0

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
v0_re = v0.reshape((3, 3))
v0_re

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ou, então,

In [28]:
v1 = np.random.randint(1, 6, (4, 3))
v1

array([[1, 3, 4],
       [1, 4, 2],
       [1, 5, 2],
       [3, 2, 4]])

In [29]:
v1_re = v1.reshape(3, 4)
v1_re

array([[1, 3, 4, 1],
       [4, 2, 1, 5],
       [2, 3, 2, 4]])

caso não saiba a combinação necessária para reformular o array pode-se usar o -1:

In [47]:
v1.reshape(3, -1)

array([[1, 3, 4, 1],
       [4, 2, 1, 5],
       [2, 3, 2, 4]])

ou

In [48]:
v1.reshape(-1, 2)

array([[1, 3],
       [4, 1],
       [4, 2],
       [1, 5],
       [2, 3],
       [2, 4]])

#### unique()
---

quando um array tem muitos valores repetidos, pode-se usar esta função para que cada valor apareça apenas uma vez.

In [30]:
rep = np.array([1, 1, 2, 3, 4, 4, 5, 6, 5, 7, 8, 9, 1])
rep

array([1, 1, 2, 3, 4, 4, 5, 6, 5, 7, 8, 9, 1])

In [31]:
np.unique(rep)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

com o parâmetro `return_counts=True`, a função `.unique()` retorna um segundo array que informa a quantidade de vezes que cada número se repete:

In [32]:
np.unique(rep, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([3, 1, 1, 2, 2, 1, 1, 1, 1]))

observe que a posição no segundo array corresponde à posição na primeira. Ou seja, no primeiro array o 3 está na posição 2. indo então à posição 2 no segundo array, tem-se o número 1, indicando que o 3 só aparece 1 vez no array original.